### ISSUE TITLE
btstack_audio_esp32.c fails to compile with ESP-IDF 4.1

### ISSUE THREAD

**Issue by ecc1** [bluekitchen/btstack#327]
master branch (currently at v1.2-21-gcbf5eb7c7) fails to build btstack_audio_esp32.c with ESP-IDF v4.1, with the following error:
```
/opt/esp/idf/components/btstack/btstack_audio_esp32.c: In function 'btstack_audio_esp32_sink_init':
/opt/esp/idf/components/btstack/btstack_audio_esp32.c:140:45: error: 'I2S_COMM_FORMAT_STAND_I2S' undeclared (first use in this function); did you mean 'I2S_COMM_FORMAT_I2S'?
                     .communication_format = I2S_COMM_FORMAT_STAND_I2S,
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
                                             I2S_COMM_FORMAT_I2S
```

**Comment by mringwal** [comment]
please use develop branch until next master update which should happen later this week.

**Comment by mringwal** [comment]
(or if I got this wrong, use esp-idf master branch)

**Comment by mringwal** [comment]
It's been on master for a while now... :)
