### ISSUE TITLE
"develop" branch does not compile with esp-idf 4.0.1

### ISSUE THREAD

**Issue by ricardoquesada** [bluekitchen/btstack#308]
Using develop branch (hash: aad97216186d8a961b020b0c707f006ace68c167)

When I compile my project it returns:

```
Toolchain path: /home/riq/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: esp-2019r2
Compiler version: 8.2.0
Python requirements from /home/riq/bin/esp/esp-idf/requirements.txt are satisfied.

App "firmware" version: release_firmware_v1.0.0-12-g60f
CC build/btstack/src/classic/avdtp.o
/home/riq/bin/esp/esp-idf/components/btstack/src/classic/avdtp.c: In function 'avdtp_handle_sdp_client_query_result':
/home/riq/bin/esp/esp-idf/components/btstack/src/classic/avdtp.c:800:9: error: 'status' may be used uninitialized in this function [-Werror=maybe-uninitialized]
         avdtp_handle_sdp_query_failed(connection, status);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
```

Simple fix:
in `avdtp.c` line initialize status with:

```
uint8_t status = ERROR_CODE_SUCCESS;
```
